<?php


namespace Zedstar16\SBEvent\tasks;


use pocketmine\scheduler\AsyncTask;
use pocketmine\Server;
use Zedstar16\SBEvent\Base;

class AsyncMoneyUpdateTask extends AsyncTask
{
    /** @var String */
    public $result;
    /** @var \Volatile */
    public $list;

    public function __construct(array $list)
    {
        $this->list = $list;
    }

    public function onRun()
    {
        $list = (array)$this->list;
        arsort($list);
        $this->result = serialize((array)$list);
    }

    public function onCompletion(Server $server)
    {
        Base::$topmoney = unserialize($this->result);
        parent::onCompletion($server); // TODO: Change the autogenerated stub
    }

}